# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.1.8
_src_path: https://github.com/frkl-dev/python-project-template.git
anaconda_user: ''
email: markus@frkl.dev
full_name: Markus Binsteiner
github_user: hostuser
project_licenses:
- MIT
project_name: Berlin Events Explorer
project_short_description: Parse and explore Berlin music events with enriched venue
    and performer metadata.
